library(fixest)
library(data.table)
data <- read.csv("F:\\NETDATA\\SciSciNetPaperData\\1950-2017\\paperforReg.csv")

reg1<-feols(log(C5+1)~TeamAgeMean+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg2<-feols(log(C5+1)~TeamAgeDiversity+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg3<-feols(log(C5+1)~TeamAgeMean+TeamAgeDiversity+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg4<-feols(log(C5+1)~TeamAgeMean+TeamAgeMean2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg5<-feols(log(C5+1)~TeamAgeDiversity+TeamAgeDiversity2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg6<-feols(log(C5+1)~TeamAgeMean+TeamAgeDiversity+TeamAgeDiversity2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg7<-feols(log(C5+1)~TeamAgeMean+TeamAgeMean2+TeamAgeDiversity+TeamAgeDiversity2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
write.csv(etable(reg1,reg2,reg3,reg4,reg5,reg6,reg7) , "G:\\A J YANG PAPER\\Collaboration\\With Meijun Liu\\Age diveristy\\figs1\\reg11.csv")

reg1<-feglm(hit~TeamAgeMean+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data,family = "binomial", se = "standard")
reg2<-feglm(hit~TeamAgeDiversity+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data,family = "binomial", se = "standard")
reg3<-feglm(hit~TeamAgeMean+TeamAgeDiversity+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data,family = "binomial", se = "standard")
reg4<-feglm(hit~TeamAgeMean+TeamAgeMean2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data,family = "binomial", se = "standard")
reg5<-feglm(hit~TeamAgeDiversity+TeamAgeDiversity2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data,family = "binomial", se = "standard")
reg6<-feglm(hit~TeamAgeMean+TeamAgeDiversity+TeamAgeDiversity2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data,family = "binomial", se = "standard")
reg7<-feglm(hit~TeamAgeMean+TeamAgeMean2+TeamAgeDiversity+TeamAgeDiversity2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data,family = "binomial", se = "standard")
write.csv(etable(reg1,reg2,reg3,reg4,reg5,reg6,reg7) , "G:\\A J YANG PAPER\\Collaboration\\With Meijun Liu\\Age diveristy\\figs1\\reg12.csv")

reg1<-feols(RaoStirling_percentile~TeamAgeMean+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg2<-feols(RaoStirling_percentile~TeamAgeDiversity+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg3<-feols(RaoStirling_percentile~TeamAgeMean+TeamAgeDiversity+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg4<-feols(RaoStirling_percentile~TeamAgeMean+TeamAgeMean2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg5<-feols(RaoStirling_percentile~TeamAgeDiversity+TeamAgeDiversity2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg6<-feols(RaoStirling_percentile~TeamAgeMean+TeamAgeDiversity+TeamAgeDiversity2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg7<-feols(RaoStirling_percentile~TeamAgeMean+TeamAgeMean2+TeamAgeDiversity+TeamAgeDiversity2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
write.csv(etable(reg1,reg2,reg3,reg4,reg5,reg6,reg7) , "G:\\A J YANG PAPER\\Collaboration\\With Meijun Liu\\Age diveristy\\figs1\\reg13.csv")

reg1<-feols(Disruption_percentile~TeamAgeMean+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg2<-feols(Disruption_percentile~TeamAgeDiversity+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg3<-feols(Disruption_percentile~TeamAgeMean+TeamAgeDiversity+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg4<-feols(Disruption_percentile~TeamAgeMean+TeamAgeMean2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg5<-feols(Disruption_percentile~TeamAgeDiversity+TeamAgeDiversity2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg6<-feols(Disruption_percentile~TeamAgeMean+TeamAgeDiversity+TeamAgeDiversity2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
reg7<-feols(Disruption_percentile~TeamAgeMean+TeamAgeMean2+TeamAgeDiversity+TeamAgeDiversity2+log(Reference_Count)+Reference_Age_Mean+log(Title_Length)+AvgPastPubs+Funding+log(Team_Size)+log(Institution_Count)+log(Country_Count)|Year+ FieldID, data, se = "standard")
write.csv(etable(reg1,reg2,reg3,reg4,reg5,reg6,reg7) , "G:\\A J YANG PAPER\\Collaboration\\With Meijun Liu\\Age diveristy\\figs1\\reg2.csv")